### ISSUE TITLE
Read token attributes?

### ISSUE THREAD

**Issue by abrasat** [datalust/superpower#100]
When iterating the tokens generated by the tokenizer, is it possible to check if any TokenAttribute (category, example or description) is set, and, if yes, to get their values ? It would be also interesting to be able to check directly if the token list contains any token from a certain category.

**Comment by nblumhardt** [comment]
Hi - yes, the token list is just a list of tokens that can be iterated over/processed using `foreach`, Linq etc. - can you send more details/pseudocode if this doesn't help? Cheers!

**Comment by abrasat** [comment]
For instance these would be some tokens
```
  [Token(Category = "placeholder", Example = "%1")]
  Placehiolder1,
  [Token(Category = "placeholder", Example = "%2")]
  Placehiolder2,
  [Token(Category = "placeholder", Example = "%3")]
  Placehiolder3,
  [Token(Category = "comment", Example = "//")]
  Comment1,
  [Token(Category = "comment", Example = "///")]
  Comment2,
  [Token(Category = "assignment", Example = ":=")]
  Assign,
  [Token(Example = "(")]
  LeftParen,
  [Token(Example = ")")]
  RightParen,
  [Token(Example = ",")]
  Comma,
```
And these would be some strings to tokenize and parse
```
var str1 = "#this is a comment line";
```
```
var str2 = "var a := b";
```
```
var str3 = "printf("Hello %1")"
```
For instance, it should be checked if a string to parse contains tokens from the "placeholder" category

**Comment by nblumhardt** [comment]
Thanks for the follow-up. No, category information isn't exposed right now - you'd need to look it up manually based on `Token<T>.Kind`.

**Comment by abrasat** [comment]
Ok, thanks
