### ISSUE TITLE
Command style declaration?

### ISSUE THREAD

**Issue by Shadowblitz16** [datalust/superpower#102]
is it possible to use this library without linq?
it's hard to grasp with my tiny brain.

something more of a sequence command style would be nice

**Comment by nblumhardt** [comment]
The couple of sequencing examples in https://github.com/datalust/superpower/pull/94#issue-287345161 don't use Linq; HTH!

**Comment by Shadowblitz16** [comment]
I mean specifically doing things like..
```

        static readonly TextParser<(char, char, char)> SequenceParser =
            Parse.Sequence(
                Character.Digit,
                Character.Digit,
                Character.Digit)
                .Select(t => t);
```

it would be nice to be able to do something like...
```
        static readonly TextParser<(char, char, char)> SequenceParser(Parser p)
        {
           p.AddSequence(Character.Digit);
           p.AddSequence(Character.Digit);
           p.AddSequence(Character.Digit);
           return p.Select();
        }
```

**Comment by nblumhardt** [comment]
Thanks for the suggestion. It'd be interesting to try experimentally building an API like this on top of Superpower - I'd prefer keeping the API here as small as possible (it's already quite broad to maintain/document), but if you give this a go, I'd love to hear how it turns out!
