### ISSUE TITLE
visual editor for superpowers that parses to executable xml

### ISSUE THREAD

**Issue by Shadowblitz16** [datalust/superpower#103]
I think superpower should get some sort of gui that you can design your own language and export it to executable xml or json.

this would make it stand out from other parser libraries and make it more friendly.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! 👍 Priorities and time constraints make this infeasible right now, but it'd be neat to hear about any projects along these lines. Cheers!

**Comment by driekus77** [comment]
I had more or less the same idea to get (E)BNF out of my TokenListParser collection in order to generate a syntax diagram or something else.

But this begins with if the TokenListParser provides META information? I can't find any or looking wrong?
