### ISSUE TITLE
More documentation and possible english tutorial videos?

### ISSUE THREAD

**Issue by Shadowblitz16** [datalust/superpower#110]
Can we get more documentation and possibly a english tutorial series?
I would love to learn how to possibly make a lua like language and maybe add some features to it.

**Comment by nblumhardt** [comment]
Thanks for the suggestion! Documentation work is ongoing :-)

It's not possible for us to write more tutorials right now - but the concepts should be similar to those in resources like https://interpreterbook.com/ - starting there would be great (although you need to mentally translate to C# :-)).

**Comment by Shadowblitz16** [comment]
thats too bad

**Comment by EuroEager2008** [comment]
Any progress?

**Comment by nblumhardt** [comment]
@EuroEager2008 Hi! Have you watched https://www.youtube.com/watch?v=t4dYy6P3JuA ?

**Comment by EuroEager2008** [comment]
I watched it today and it helps, but I an too new to this (I mean parsing, never really tried before).
I asked a more specific question here: https://stackoverflow.com/questions/64268942/using-superpower-to-parse-simple-block-oriented-data-structures
If you care, please just guide me a bit in how to structure tokenizer(s) and parsers for this simple case.
Should I define a tokenizer (and token enum) for each "block type" or just one for the whole span (textfile), several parsers etc.?

**Comment by nblumhardt** [comment]
Thanks for your reply, @EuroEager2008 👍 - I'd love to help (super interesting subject area!) but I can't squeeze the time right now to dig in deeper; there should be a lot of relevant material out there discussing tokenization, parser combinators, and the like, though it takes some time to work through. Good luck with it!
