### ISSUE TITLE
Unit Testing?

### ISSUE THREAD

**Issue by Shadowblitz16** [datalust/superpower#121]
How do I unit test a parser?
```
        [Test]
        public void Chr()
        {
            Parsers.Chr.TryParse("'a'")
        }
```

**Comment by nblumhardt** [comment]
Hi! You can see some examples in projects like https://github.com/serilog/serilog-expressions/blob/dev/test/Serilog.Expressions.Tests/ExpressionParserTests.cs

Hope this helps,
Nick
