### ISSUE TITLE
Guidance on how to achieve some level of error recovery

### ISSUE THREAD

**Issue by chrisspre** [datalust/superpower#124]
Is there any tips or guidance how to achieve some sort of error recovery for a superpower parser so that the parser can report multiple, independent syntactical errors?

Without extra caution a superpower parser stops parsing when it discovers an error which means an end-user needs to fix one error at a time.
Typically programming languages show multiple errors in one file. My understanding is that these parsers detect one error per "statement" (a common production rule) and skip over some text until the next statement is discover.
How can this be achieved in superpower?

**Comment by nblumhardt** [comment]
Hi @chrisspre - unfortunately, no, this is unexplored territory for Superpower. It would be extremely interesting to hear what you come up with, if you decide to dig in further. My guess is that some of Superpower (as it stands today) could be reused, but there would need to be fairly deep changes to support recovery/reporting of multiple errors.

Best regards,
Nick
