### ISSUE TITLE
[Request] Need a new introductory blog for v2 (or v3)

### ISSUE THREAD

**Issue by arisliang** [datalust/superpower#128]
There's a nice introductory blog at [here](https://nblumhardt.com/2016/09/superpower/). While very nice, it's written in 2016, and targeting v1 (it seems).

It seems much has changed and improved after a few years, for example #26 , the library has probably advanced enough to warrant another write-up to get new user up to speed.

**Comment by nblumhardt** [comment]
Thanks for raising this. I think the best way to focus efforts in this area would be to improve the README, which is an ongoing process. Thanks again!
