### ISSUE TITLE
[Question] Compare with ANTLR

### ISSUE THREAD

**Issue by HamedFathi** [datalust/superpower#13]
Hi
Thanks for you great library.

Is it possible to make a comparison with the ANTLR ? (pros, cons, features, ...)
Can you get a road map?

for example, We don't have any Visitor like ANTLR so I think we should define event for each steps.
or EBNF syntax can be useful in some scenarios too however Fluent Syntax is brilliant .

It's great that we have a library like ANTLR based on C#.NET entirely.

**Comment by nblumhardt** [comment]
Hi @HamedFathi - thanks for dropping by.

I'd love to be able to do this, but it's a fairly big task as any comparison would have to either assume some level of familiarity with ANTLR, or else explain how ANTLR works in addition to Superpower.

All the best,
Nick
