### ISSUE TITLE
Thank you for writing superpower

### ISSUE THREAD

**Issue by djluck** [datalust/superpower#139]
I just wanted to drop a message to firstly thank you for this project- it really does live up to it's name and it's been a fascinating introduction to parser combinators. 

Secondly, I've been working on a parser for the PromQL language (https://github.com/djluck/PromQL.Parser) if you wanted another example to list in the README.

Cheers!

**Comment by nblumhardt** [comment]
Done! Thanks for the heads-up, James 👍 

Glad you've been enjoying Superpower; parser combinators are still one of my absolute favorite tools, too 😄
