### ISSUE TITLE
How to handle consecutive delimiters

### ISSUE THREAD

**Issue by woha** [datalust/superpower#158]
I'm trying to parse an input where the elements are separated by semicolon, but I'm unable to get it working for consecutive delimiters.

Example: `var input = "TEST123;TEST456;;HALLO";`

And I'm getting `Syntax error (line 1, column 17): unexpected `;`, expected TgwComCon value.`

(Using `.ManyDelimitedBy(Token.EqualTo(TgwComConToken.Semicolon)).AtEnd();`).

Is there a way to return `null` or `string.Empty` for "empty" elements?

**Comment by marklauter** [comment]
I'm not 100% sure, but I think the parser it's up to the "this parser" to be able to parse an empty or zero result. 
parser.ManyDelim..
^ parser must be able to succeed with something like "" or "\0" input.

**Comment by woha** [comment]
Thank you @marklauter. I think you are totally correct.
I've tried that, but failed.
Could you please give me an example / idea of how to parse such an empty result?

**Comment by marklauter** [comment]
Full disclosure, I'm new to parser combinators and am still working my way through Graham Hutton's and Erik Meijer's 1996 paper, but I will attempt a sample today after work.

**Comment by marklauter** [comment]
I wrote a very simple tokenizer with a "null value" parser that detects consecutive ';' characters. The semicolons can be separated by whitespace. Readme shows output. I hope it's useful. 

https://github.com/marklauter/superpower-delimited-combinator

**Comment by woha** [comment]
@marklauter This works simply perfect!

Thank you very much for your time and help, highly appreciated.

Looks like I should start reading Graham Hutton's and Erik Meijer's paper as well - I wish you some enlightening moments reading it.

Once again - thank you!

**Comment by marklauter** [comment]
I'm so glad this idea worked for you. Happy parsing.
