### ISSUE TITLE
dotnet 8 upgrade?

### ISSUE THREAD

**Issue by marklauter** [datalust/superpower#159]
Are there any plans to upgrade SP to dotnet 8? 
6 and 7 are almost OOS, and the Nuget release is still dotnet 5.
If there is interest from Datalust / Nick, and it would not be a waste of my time, then I would be happy to do the work and submit a PR.

**Comment by nblumhardt** [comment]
Hi Mark, thanks for the offer. It looks like `dev` already targets `net6.0`, which will still be a good target for many years to come, but the tooling would benefit from an update to .NET 8 norms, and adding `net8.0` to the list of explict TFMs would also be welcome, if you're keen to take a look :+1:

**Comment by marklauter** [comment]
Cool. I will have a look. 
Is there a contributer guidelines I should read first?

**Comment by nblumhardt** [comment]
Hi Mark,

No, there are no formal guidelines, but as a rule of thumb, aiming to keep the PR fairly minimal is the way to go: it'll be easier and quicker to review and merge if the changes are nonbreaking, incremental updates, without introducing new patterns, dependencies, etc.

Any broader changes can then be bundled up separately into later PRs after some discussion.

Hope this covers what you meant, let me know if you need a hand, though!

Best regards,
Nick

**Comment by marklauter** [comment]
Thanks, Nick. I submitted a PR. I hope the global.json SDK change doesn't cause complications.

**Comment by nblumhardt** [comment]
Looks good, thanks Mark!
