### ISSUE TITLE
Simpler tokenization

### ISSUE THREAD

**Issue by nblumhardt** [datalust/superpower#26]
Currently, the need to write a tokenizer makes it hard to get started with Superpower. Almost prohibitively so, except for the most motivated newcomers :-)

Generating high-performance, general, tokenizers is a bit more than we can bite off here in the short term, but that doesn't preclude us from making the experience better. At the expense of some raw performance, it's possible to generate fairly useful tokenizers using `TextParser<T>`s as recognizers.

In v2, this is the model I'd like to propose:

```csharp
var tokenizer = new TokenizerBuilder<SExpressionToken>()
    .Ignore(Span.WhiteSpace)
    .Match(Character.EqualTo('('), SExpressionToken.LParen)
    .Match(Character.EqualTo(')'), SExpressionToken.RParen)
    .Match(Numerics.Integer, SExpressionToken.Number, requireDelimiters: true)
    .Match(Character.Letter.IgnoreThen(Character.LetterOrDigit.AtLeastOnce()),
        SExpressionToken.Atom, requireDelimiters: true)
    .Ignore(Comment.ShellStyle)
    .Build();

var tokens = tokenizer.TryTokenize("abc (123 def) # this is a comment");
Assert.True(tokens.HasValue);
Assert.Equal(5, tokens.Value.Count());
```

Compare this with the by-hand version in: https://github.com/datalust/superpower/blob/dev/test/Superpower.Tests/SExpressionScenario/SExpressionTokenizer.cs#L10 - at least 30 significant lines of fairly dense code, without even supporting comments.

The proposed `TokenizerBuilder` can accept any text parser as a recognizer, and using the `requireDelimiters` argument, can deal with the awkward `"is null"` vs `"isnull"` case using a one-token lookahead.

The downside is that tokenizer run-time increases linearly with respect to the number of matches attempted. This probably isn't noticeable for small grammars like the one above, but larger grammars can do much better with a hand-written replacement. We might be able to extend the builder with some optimizations to claw this perf back, down the line, or add a table-based alternative.

**Comment by nblumhardt** [comment]
`TokenizerBuilder` is in on `dev`. Leaving this open until one remaining TODO is covered - the tokenizer, if it fails, needs to report the error at the most accurate point; i.e. if one recognizer failed after consuming 0 chars, and another after 10 chars, the latter's results should be surfaced.

**Comment by SuperJMN** [comment]
"Motivated". Did you call me? ;)

**Comment by SuperJMN** [comment]
I'm taking a look tomorrow! Promise :)

**Comment by SuperJMN** [comment]
OK, I'm trying to translate one of my tokenizers to the TokenizerBuilder DSL :)

If I understand it well, this tokenizer will match 
 - the **boolean operator '=='** 
 - the assignment **operator '='**.
```
var tokenizer = new TokenizerBuilder<LangToken>()
                .Match(Character.EqualTo('=').IgnoreThen(Character.EqualTo('=')), LangToken.DoubleEqual)
                .Match(Character.EqualTo('='), LangToken.Equal)
                .Build();
```
Is it a better way to do it? For me, the matching of '==' is a bit cumbersome.

**Comment by SuperJMN** [comment]
Another question that raises is the matching of keywords.

Right now I found I could do with this construction:

```
builder
    .Match(Span.EqualTo("if"), LangToken.If)
    .Match(Span.EqualTo("while"), LangToken.While)
    .Match(Span.EqualTo("do"), LangToken.Do)
    .Match(Span.EqualTo("for"), LangToken.For)
   ....
```

Is this the best way to match keywords? :)

**Comment by SuperJMN** [comment]
I have just discovered another use case:

If you want to make the tokenizer to convert any sequence of whitespace characters to a single token, for example: LangToken.Whitespace, should we do it like this?
```
builder
    .Match(Character.WhiteSpace.AtLeastOnce(), LangToken.Whitespace)
```

**Comment by SuperJMN** [comment]
@nblumhardt Nicholas, using the Tokenizer Builder has relieved the pains of creating one manually A LOT! For me it's a big success. I've created an equivalent tokenizer using the Builder in less than 10 minutes. Wow!

**Comment by SuperJMN** [comment]
BTW, the tokenizer I have right now is this. I've only added the tokens that I'm using right now, for my tests. It corresponds to a subset of tokens of a typical C language parser.

return new TokenizerBuilder<LangToken>()
                .Match(Character.WhiteSpace.AtLeastOnce(), LangToken.Whitespace)
                .Match(Span.EqualTo("=="), LangToken.DoubleEqual)
                .Match(Character.EqualTo('='), LangToken.Equal)
                .Match(Character.EqualTo('('), LangToken.LeftParenthesis)
                .Match(Character.EqualTo(')'), LangToken.RightParenthesis)
                .Match(Character.EqualTo('{'), LangToken.LeftBrace)
                .Match(Character.EqualTo('}'), LangToken.RightBrace)
                .Match(Character.EqualTo(';'), LangToken.Semicolon)
                .Match(Span.EqualTo("if"), LangToken.If, true)
                .Match(Span.Regex(@"\w[\w\d]*"), LangToken.Identifier, true)
                .Build();

**Comment by Platzer** [comment]
Sry for barging in... I've got a remark to @SuperJMN comment on keyword parsing. How would you build a parser for this:
```
if whileRunning == true
```
so it is generating these tokens:
```
- LangToken.If
- LangToken.Whitespace
- LangToken.Identifier
- LangToken.Whitespace
- LangToken.DoubleEqual
- LangToken.Whitespace
- LangToken.True
```
because (I think, didn't try)
```
builder
    ...
    .Match(Span.EqualTo("while"), LangToken.While)
    ...
```
will match the `whileRunning` identifier as `LangToken.If`?

**Comment by SuperJMN** [comment]
@Platzer I've tried with this most complete version of the parser and it works. I think it's not only because the order of the Match calls does matter, but also because I set the "requireDelimiters" option to true in both keyworkds  and identifiers (it's false by default).

This is the code I tested:

```
    public class TokenizerSpecs
    {
        [Theory]
        [MemberData(nameof(TokenData))]
        public void TokenizationTest(string code, IEnumerable<LangToken> tokens)
        {
            var sut = CreateSut();
            var actual = sut.Tokenize(code).Select(t => t.Kind);
            var expected = tokens;

            actual.Should().BeEquivalentTo(expected);
        }

        public static IEnumerable<object[]> TokenData()
        {
            return new List<object[]>()
            {
                new object[] {"==", new List<LangToken>() {LangToken.DoubleEqual},},
                new object[] {"=", new List<LangToken>() {LangToken.Equal},},
                new object[] {"ifSomething", new List<LangToken>() {LangToken.Identifier},},
                new object[]
                {
                    "if whileRunning == true", 
                    new List<LangToken>()
                    {
                        LangToken.If,
                        LangToken.Whitespace,
                        LangToken.Identifier,
                        LangToken.Whitespace,
                        LangToken.DoubleEqual,
                        LangToken.Whitespace,
                        LangToken.True,
                    },
                },
            };
        }

        private Tokenizer<LangToken> CreateSut()
        {
            return TokenizerFactory.Create();
        }
    }
```

and the Tokenizer is this:

´´´
    public static class TokenizerFactory
    {
        public static Tokenizer<LangToken> Create()
        {
            return new TokenizerBuilder<LangToken>()
                .Match(Character.WhiteSpace.AtLeastOnce(), LangToken.Whitespace)
                .Match(Span.EqualTo("=="), LangToken.DoubleEqual)
                .Match(Character.EqualTo('='), LangToken.Equal)
                .Match(Character.EqualTo('('), LangToken.LeftParenthesis)
                .Match(Character.EqualTo(')'), LangToken.RightParenthesis)
                .Match(Character.EqualTo('{'), LangToken.LeftBrace)
                .Match(Character.EqualTo('}'), LangToken.RightBrace)
                .Match(Character.EqualTo(';'), LangToken.Semicolon)
                .Match(Span.EqualTo("if"), LangToken.If, true)
                .Match(Span.EqualTo("while"), LangToken.While, true)
                .Match(Span.EqualTo("true"), LangToken.True, true)
                .Match(Span.EqualTo("false"), LangToken.False, true)
                .Match(Span.Regex(@"\w[\w\d]*"), LangToken.Identifier, true)
                .Build();
        }
    }
```

**Comment by nblumhardt** [comment]
@SuperJMN looking good! Curious - why does your grammar need whitespace tokens?

**Comment by Platzer** [comment]
@nblumhardt if you want to keep the users format and highlight the errors with some squiggles you would need to know how many whitespaces the user entered (see: [NDC London How to parse a file - Matt Ellis](https://www.youtube.com/watch?v=0b3PiOoHUp0).

**Comment by SuperJMN** [comment]
@nblumhardt It seems I asked myself the wrong question: "how can my grammar ignore whitespaces?" :) To tell the truth, I just added them because it seemed unnatural at first glance, but now that you say, it's better to remove them because it will make my parsers simpler :)

**Comment by nblumhardt** [comment]
@Platzer thanks for the link - will try to check it out :-)

@SuperJMN removing whitespace definitely does make constructing the parser a bit simpler 👍

**Comment by Platzer** [comment]
@nblumhardt `TokenizerBuilder` is an amazing feature 👍 
Yesterday i refactored the tokenizer of o custom DSL from 200 lines of code to easy readable 30 lines of `TokenizerBuilder` code in less than 40 minutes and just 2 of ~200 test are failing. It is really easy to get started!

**Comment by nblumhardt** [comment]
That's great to hear, @Platzer!

**Comment by straatvark** [comment]
A question please: I have a similar situation as the following:
 .Match(Span.EqualTo("while"), LangToken.While) that match 'whileRunning'

I have created this helper method:
        public static TextParser<TextSpan> BuildTextParserEqualTo(string equalTo)
        {
            return Span.EqualTo(equalTo);
        }

That I call from here:
var tokenizerBuilder = new TokenizerBuilder<InputToken>();
                tokenizerBuilder.Ignore(Span.WhiteSpace);
                tokenizerBuilder.Match(BuildTextParserEqualTo("and"), InputToken.And);
                tokenizerBuilder.Match(Span.NonWhiteSpace, InputToken.None);
                return tokenizerBuilder.Build();

But the "and" would get matched in this text: "aaa bbb ccc andDDD" - unwanted in my case unfortunately.

How do I get it matched for only the "and" in: "aaa bbb ccc and DDD", i.e. only for a stand-alone word / token?

(I tried the Regex approach as well, but that also seems to ignore the $ at the end of my expression)

Any help would be much appreciated.

> Sry for barging in... I've got a remark to @SuperJMN comment on keyword parsing. How would you build a parser for this:
> 
> ```
> if whileRunning == true
> ```
> 
> so it is generating these tokens:
> 
> ```
> - LangToken.If
> - LangToken.Whitespace
> - LangToken.Identifier
> - LangToken.Whitespace
> - LangToken.DoubleEqual
> - LangToken.Whitespace
> - LangToken.True
> ```
> 
> because (I think, didn't try)
> 
> ```
> builder
>     ...
>     .Match(Span.EqualTo("while"), LangToken.While)
>     ...
> ```
> 
> will match the `whileRunning` identifier as `LangToken.While`?
