### ISSUE TITLE
[SOLVED / EDITED] I wanted to clarify something regarding the use of OR

### ISSUE THREAD

**Issue by xDGameStudios** [datalust/superpower#27]
I have something like this in pseudo code.

```
property = identifier + (equalsign + value).optional

method = identifier + openparenthesis + arguments + closeparenthesis;

member = method.or(property) + terminator

```

this doesn't seem to work with the error "unexpected equalsign expected openparenthesis"... when I have a property...would it be because of the identifier being common to both (property and method). or am I doing something wrong?!

**Comment by nblumhardt** [comment]
Hi! If you still need a hand with this, some kind of repro or code snippets might be needed. It's often a bit of a debugging task though - one tactic I often use is to break the grammar into small parsers and test the error reporting in each one individually. This might pinpoint what's going wrong. Cheers!

**Comment by faina09** [comment]
I have a similar issue, and yes, the problem seems to be "because of the identifier being common" (one or more). The solution is to use TRY:

member = method.Try().Or(property) + terminator

**Comment by nblumhardt** [comment]
Sounds like this is solved; please let us know if you still need a hand with it.
