### ISSUE TITLE
Use names for unprintable characters when describing expectations

### ISSUE THREAD

**Issue by nblumhardt** [datalust/superpower#36]
An unexpected newline will be rendered inline in the message as _unexpected `
`._ We should substitute names for these, instead showing _unexpected newline_, etc.

**Comment by BenjaminHolland** [comment]
What's the scope of this? The set of ASCII unprintables is pretty doable, but UTF seems like a nightmare.

**Comment by nblumhardt** [comment]
@BenjaminHolland I think dealing with ASCII would be a significant improvement - taking on Unicode is, as you say, a bit more involved :-)

The list in https://docs.microsoft.com/en-US/dotnet/api/system.char.iswhitespace?view=netframework-4.7.2 suggests the whitespace categories might not be _too_ big for us to track a mapping onto names; perhaps we could attempt:

```
unexpected character HAIR SPACE (U+200A)
```

Thoughts?

**Comment by BenjaminHolland** [comment]
I kept with the formatting for the per-existing white space character names. I do think adding the character code in is a good idea though

**Comment by AndrewSav** [comment]
@nblumhardt looks like this one is done and merged in that PR and can be closed?

**Comment by nblumhardt** [comment]
Thanks @AndrewSav :+1:
