### ISSUE TITLE
Partial parsing results for completions

### ISSUE THREAD

**Issue by skyne98** [datalust/superpower#43]
Hey there! Is there a way to get a list of potential parse results, when there is a parse error? This may be very useful for providing auto-completions in the editors by analyzing the partial AST.

Thanks!

**Comment by skyne98** [comment]
@nblumhardt, to be honest, I such case I see only two solutions:

* as commonly done, you can always create additional parsers for the "wrong" situations
* avoid this problem altogether and provide completions only for correctly parsed programs (identifier completions, for example)

**Comment by skyne98** [comment]
The first solution will partially solve the problem, however, we all know that you cannot physically cover all the scenarios. Also, the codebase will become a big mess, trying to make parsers for all the "wrong" paths a user can take.
The second one is feasible in the beginning,  as most of the times you want exactly that type of completions. However, in that case you will have a very limited set of possible completions you can provide.

Either of those ways won't provide a full experience for the user. The only practical solution I see is having a parser provide its state in a form of a list of "possible" trees, to solve the possible ambiguity problem of parsing incomplete sources.

**Comment by skyne98** [comment]
Also, you can try to use the type data of the previous successful compilations as the source of truth. It will allow you to query data about the failed token, based on that info and provide a meaningful set of completions. Hmm, it won't even require any kind of magic. Interesting!

**Comment by nblumhardt** [comment]
Thanks for sharing your thoughts. I might close this one as I don't think there's a direction to follow here, yet, but keep us in the loop with your investigations! :-)
