### ISSUE TITLE
How to use Token.Sequence()

### ISSUE THREAD

**Issue by powerdude** [datalust/superpower#44]
Hello,

I'm not sure how to use `Token.Sequence()` like `Token.EqualTo()`.  Can you provide an example?  I'm trying to do this:

 ```
public static TokenListParser<MyToken, int> MySpecialNumber = Token.Sequence(MyToken.Number, MyToken.Word).Apply(Numerics.IntegerInt32); 
```

but it fails because the text parser can't take a series of tokens.  What is a valid use case for this method or what kind of parser do i have to create to use `Apply`?

**Comment by nblumhardt** [comment]
Hi @powerdude - 

In this case you probably want something like:

```csharp
public static TokenListParser<MyToken, int> MySpecialNumber = 
  Token.EqualTo(MyToken.Number).Apply(Numerics.IntegerInt32))
    .Then(n => Token.EqualTo(MyToken.Word).Value(n));
```

HTH!
Nick

**Comment by dhowe** [comment]
Still be good to have an example of how this function works...

**Comment by nblumhardt** [comment]
It's a helper for cases like: `Token.Sequence(Token.Yield, Token.Break)` 👍
