### ISSUE TITLE
parsing comments

### ISSUE THREAD

**Issue by fcavaco** [datalust/superpower#47]
hi, I am trying to parse multiline comments with delimiters as defined for C line languages using Superpower but contrary to Sprache cannot find a lot out there to guide me. tried a few possibilities with no luck.
e.g.

/* this is a comment */
or
/* this is  a
comment */

public static readonly TextParser<string> MultiLineComment =
        from first in OpenMultilineComment
        from rest in **Character.AnyChar.ManyDelimitedBy**(CloseMultilineComment)
        from last in CloseMultilineComment
        select new string(rest);

the code above returns only one char for "rest" and I cannot work out why to be honest!?

**Comment by nblumhardt** [comment]
Hi, thanks for the post.

Have you checked out the built-in `Comment.CStyle` parser? https://github.com/datalust/superpower/blob/dev/src/Superpower/Parsers/Comment.cs#L75

Cheers,
Nick

**Comment by fcavaco** [comment]
Hi Nick,
Many thanks for replying back.
The answer is yes, have seen that parser but could not figure out how to use it from within my declared Comment. E.g

`        public static readonly TextParser<string> MultiLineComment =
            from open in OpenMultilineComment
            from rest in Character.AnyChar.ManyDelimitedBy(CloseMultilineComment)
            from close in CloseMultilineComment
            select rest.AsString();

        public static readonly TextParser<string> Comment 
            = SingleLineComment.Try()
            .Or(MultiLineComment.Try());
`

Is it the case can only use it from within a tokenizer?

**Comment by nblumhardt** [comment]
Sorry about the lack of an answer here - I hope you figured this one out; if not, please jump back in! :-)

(There are two main approaches to handling comments; discard them at the tokenization stage, or, create a combinator that attaches leading/trailing trivia to the results of other parsers; it sounds like you're after the latter.)
