### ISSUE TITLE
Function Calls - Recursive / Circular Grammars

### ISSUE THREAD

**Issue by skyne98** [datalust/superpower#48]
Hello there everyone!

I have been struggling to parse recursive function calls, as implementing both recursive and iterative grammars seems impossible.

Is there some kind of solution? 
Thanks!

**Comment by nblumhardt** [comment]
Hi @skyne98 - not sure what problem you are hitting, but it's possible you need to use the `Parse.Ref(() => x)` mechanism to lazily reference a parser that hasn't yet been constructed?

Most of the examples in the README are recursive, so there might be some useful info there. Please send some more details if you need them clarified at all.

Cheers,
Nick

**Comment by skyne98** [comment]
@nblumhardt the main problem is that the function call grammar is right-recursive and I wasn't able to use any available tools to implement that. However, I managed to pretty easily write a RightRec parser, working similar to Chain or ChainRight. 
I can probably make a pull request with some additions for right-recursive grammars, if the community is ok with that :smile:

**Comment by nblumhardt** [comment]
Hi @skyne98, thanks for the follow-up; the grammar seems quite unusual - would `5 () ()` be a valid production? If you can post an example input I would love to try to figure out whether there's an alternative way to structure the parser. Cheer!

**Comment by skyne98** [comment]
Hey, @nblumhardt, let's imagine you have a function foo, that has a type of (int)->(void)->int, which in JS will look something like this:
```javascript
function foo(x) {
    return function() {
        return x * x;
    }
}
```
Now we want to call it:
```
let result = foo(2)() // which will return 4
```

Such grammar is required for languages, where there are pointers to functions, or functions can be passed as a value. 
Nevertheless, I still think that there should be an extension for right-recursive grammars. Cheers!

**Comment by nblumhardt** [comment]
Thanks for the follow-up, and sorry about the long delay! Would be interesting to see how your grammar comes out with the `RightRec` helper; not sure how/where it would fit in the grand scheme of things, but curious! :-)

Cheers,
Nick
