### ISSUE TITLE
Simple tokenizer question

### ISSUE THREAD

**Issue by dhowe** [datalust/superpower#58]
I'm trying to match c-style identifiers that start with a '#' character, but to discard the hash character and keep the rest. In my attempts below the '#' is always included in the token:

```c#
static TextParser<Unit> HashIdent { get; } = Character.EqualTo('#').IgnoreThen(Identifier.CStyle).Value(Unit.Value);
```

I know I'm missing something simple...

**Comment by nblumhardt** [comment]
Hi!

The tokenizer will consider the whole span matched by the parser to be the token, regardless of the value that's returned, but, you can use `.Apply(HashIdent)` later on in the parsing stage to get the value, i.e. `Token.EqualTo(Tokens.Identifier).Apply(HashIdent)`.

For this to work you need to drop off the `Value(Unit.Value)` piece:

```csharp
static TextParser<Unit> HashIdent { get; } = Character.EqualTo('#').IgnoreThen(Identifier.CStyle)
```

HTH!

**Comment by dhowe** [comment]
Also, how do I handle the opposite case, where I want to ignore the last character?

```c#
        static TextParser<Unit> Actor { get; } =
            from name in Character.LetterOrDigit.Many()
            from last in Character.EqualTo(':')
            select Unit.Value;

**Comment by nblumhardt** [comment]
I guess this water is long under the bridge - hope you found a good solution, @dhowe - closing as stale, but keep us posted :-)
