### ISSUE TITLE
Simple parser question

### ISSUE THREAD

**Issue by dhowe** [datalust/superpower#59]
I'm trying to parse lines which consist of some free text (not including brackets {}), followed by JSON-like key-value pairs (without quotes).

I have the the key-value pairs working (thanks to your JSONParser example), but I'm stuck on how to include chars like comma and colon in the free text part (e.g., the 3rd & 4th examples below).

This seems a very basic functionality of a parser, so I'm sure I'm missing something simple... 

Some examples:

```
Hello {a:b}
Hello {a:b,c:d}
Hello, nice to meet you {a:b,c:d}
The List: A,B,C  {a:b,c:d}
```

thanks!

**Comment by AndrewSav** [comment]
@dhowe what have you tried? Where are you stuck?

I'm seeing basically two approaches here: forget the `JSONParser` example and do not use tokenization. In you simple case you can get away without it. In this case you won't care for commas and colons in your input until you actually meet the `{`.

Alternatively, if you use the tokenizer, you would need simply concatenate all these token in the rules that parses the text out side of curly brackets.

Something like 

```
var freeText = Token.EqualTo(MyToken.Comma).Or(Token.EqualTo(MyToken.Colon)).Or(Token.EqualTo(MyToken.String)).AtLeastOnce();
```

Hope this helps.

**Comment by SuperJMN** [comment]
Have you solved the problem? I can help you with the parser :)

**Comment by nblumhardt** [comment]
Closing this one as stale.
