### ISSUE TITLE
Recreate Sprache Csv Parser in Superpower

### ISSUE THREAD

**Issue by NLI-KelbyHunt** [datalust/superpower#62]
Hi @nblumhardt, I have been trying to recreate the [Sprache Csv Parser] in the test folder over in it's repository with the Superpower library.

1. I have successfully made a simple version to parse my Csv data by row but I wanted to try and recreate the slightly more comprehensive Csv parser from Sprache's tests but in Superpower.

```cs
class Program
{
    static void Main(string[] args)
    {
        var input1 = "a,b,c";
        var input2 = "d,e,f" + Environment.NewLine + "a,b,c";

        var values = CsvParser.Record.Parse(input1).ToList(); // Works for parsing individual records

        Console.WriteLine($"1:{values[0]}, 2:{values[1]}, 3:{values[2]}");

        values = CsvParser.Record.Parse(input2).ToList(); // Works just grabbing the first row

        Console.WriteLine($"1:{values[0]}, 2:{values[1]}, 3:{values[2]}");

        var test = CsvParser.Csv.Parse(input2); // Exception
    }
}

public class CsvParser
{
    private static readonly TextParser<char> CellSeparator = Character.EqualTo(',');

    private static readonly TextParser<char> QuotedCellDelimiter = Character.EqualTo('"');

    private static readonly TextParser<char> QuoteEscape = Character.EqualTo('"');

    private static TextParser<T> Escaped<T>(TextParser<T> following)
    {
        return from escape in QuoteEscape
                from f in following
                select f;
    }

    private static readonly TextParser<char> QuotedCellContent =
        Character.AnyChar.Between(QuotedCellDelimiter, Escaped(QuotedCellDelimiter));

    static readonly TextParser<char> LiteralCellContent =
        Character.ExceptIn(',', '\r', '\n');

    static readonly TextParser<string> QuotedCell =
        from open in QuotedCellDelimiter
        from content in QuotedCellContent.Try().Many()
        from end in QuotedCellDelimiter
        select new string(content);

    static readonly TextParser<string> NewLine =
        Parse.Return(Environment.NewLine);

    static readonly TextParser<string> RecordTerminator =
        Parse.Return("").AtEnd().Or(
        NewLine.AtEnd()).Try().Or(
        NewLine);

    static readonly TextParser<string> Cell =
        QuotedCell.Or(
        LiteralCellContent.Many().Select(x => new string(x)));

    public static readonly TextParser<IEnumerable<string>> Record =
        from leading in Cell
        from rest in CellSeparator.Then(_ => Cell).Try().Many()
        from terminator in RecordTerminator
        select Cons(leading, rest);

    static IEnumerable<T> Cons<T>(T head, IEnumerable<T> rest)
    {
        yield return head;
        foreach (var item in rest)
            yield return item;
    }

    public static readonly TextParser<IEnumerable<IEnumerable<string>>> Csv =
        Record.Many().AtEnd().Select(x => x.AsEnumerable());
}
```
I've tried following the [Sprache Conversion] very carefully, but, I cannot get the `TextParser<IEnumerable<IEnumerable<string>>> Csv` to work.

Exception:

```text
Exception has occurred: CLR/Superpower.ParseException
An unhandled exception of type 'Superpower.ParseException' occurred in Superpower.dll: 'Many() cannot be applied to zero-width parsers; value ParserConcept.CsvParser+<Cons>d__11`1[System.String] at position 5 (line 1, column 6).'
```

I have a feeling this is going to be a very simple problem and hoping you can provide some insight. Anything seem wrong to you? I may try and just implement one from scratch instead of converting.

P.S. Thanks for the awesome library, it's the first combinator I've used in C# and falling in love with it. It is making parsing crazy custom files I have much easier and with less code.

[Sprache Csv Parser]: https://github.com/sprache/Sprache/blob/master/test/Sprache.Tests/Scenarios/CsvTests.cs
[Sprache Conversion]: https://github.com/datalust/superpower/wiki/Sprache-Conversion

**Comment by nblumhardt** [comment]
Hi!

The problem looks to be that at the end of the input, `Cell` will still match via the `LiteralCellContent.Many()` rule, and `RecordTerminator` will also match, because of the `Parse.Return("").AtEnd()` rule, meaning there would be an essentially infinite procession of empty records at the end of the input.

A quick fix (not sure about error message quality implications?) might be to remove the `terminator` part from `Record`, and make the final rule:

```csharp
    public static readonly TextParser<IEnumerable<IEnumerable<string>>> Csv =
        Record.ManyDelimitedBy(NewLine).AtEnd().Select(x => x.AsEnumerable());
```

**Comment by NLI-KelbyHunt** [comment]
I figured the `Parse.Return("").AtEnd()` rule could potentially be hurting me.

Believe it or not, in my experimenting with this conversion, I have attempted what you suggested and it still fails with the same exception.

I am going to keep working on this today, any other suggestions appreciated.

**Comment by NLI-KelbyHunt** [comment]
Looks like it was the NewLine field/prop causing my problem, even in my simpler non-quoted Csv parser.

I changed this line
```cs
static readonly TextParser<string> NewLine = Parse.Return(Environment.NewLine);
```
to
```cs
static readonly TextParser<TextSpan> NewLine = Span.EqualTo(Environment.NewLine);
```

It now works as intended now and I am going to clean it up.

@nblumhardt Any chance you want a test or sample PR submitted?

**Comment by nblumhardt** [comment]
Aha, great! I missed that one :-)

It'd be awesome if you can post the example somewhere we can link, but I don't think we should currently add more text-parser examples to this repo, since the general not-migrating-from-Sprache usage should probably be via `TokenParser`.

**Comment by NLI-KelbyHunt** [comment]
> It'd be awesome if you can post the example somewhere we can link, but I don't think we should currently add more text-parser examples to this repo

No problem and makes sense. I will respond to this issue when I have a sample Gist created using `TextParser` method/style.

>  since the general not-migrating-from-Sprache usage should probably be via `TokenParser`.

Curious, are you saying the proper way to use Superpower is to preferably utilize the `TokenParser` instead of the built in `TextParser`'s? Is that because Token parsers have better error messaging and reporting? Or?

I am going to keep practicing with this library and also make a simple `TokenParser` to handle CSV/TSV files. Perhaps when I feel comfortable with it you could review it one day? I know your busy and will never ask for immediate review. Just a big fan of your work, style, design and architecture.

**Comment by nblumhardt** [comment]
Thanks! :D

I might have overstated the suggestion to start with token parsers; for simple things that stay simple, text parsers are probably just as good from the perspective of this library. Token parsers are able to make use of more features of Superpower, though, including the nicer error reporting and the easy handling of whitespace and comments. Not a big difference, but probably enough that I'd try starting with a token parser in most cases.

Keen to hear how you go, making the API as usable/approachable as Sprache's is an ongoing project :-) Cheers!

**Comment by nblumhardt** [comment]
Closing this as stale since we haven't looped back to it in a while, but hope all's going well!
