### ISSUE TITLE
"Structured exception data" for superpower

### ISSUE THREAD

**Issue by AndrewSav** [datalust/superpower#73]
When parsing fails an exception is thrown which includes a error message. The error message normally gives the error context, like line, and column.

In certain scenarios we are passing to the parser partial data (think templating, inlcude files, etc) to parse, and they may not correspond to what the end user will see.

The application using superpower then will need to translate the position given by the exception into an actual position relevant to the user.

Currently this is not possible without parsing the error message itself.

Can we employ ideas found in Serilog, and provide some structured data inside the exception that can be easily processed before passing onto the client?

**Comment by nblumhardt** [comment]
Included in #90.
