### ISSUE TITLE
Force .Chain() to apply at least once

### ISSUE THREAD

**Issue by RPiAwesomeness** [datalust/superpower#75]
I'm currently creating a DSL utilizing Superpower and as part of that I am using the .Chain method in my parser. However, I'm running into an issue where this isn't actually requiring the two values and operator passed in the chain method and is instead, if there is only 1 of the 2 items, simply passing that item through without requiring the operator and second item.

The parsers in question are defined as such:

```C#
public static readonly TokenListParser<Token, Operators.Operator> Boolean =
    And.Or(Or);

public static readonly TokenListParser<Token, Operators.Operator> Operator =
    Is.Or(Not).Or(LT).Or(LTE).Or(GT).Or(GTE);

public static readonly TokenListParser<Token, Expression> Unary =
    from item in Literal
    from op in Exists
    select MakeUnary(op, item);

public static readonly TokenListParser<Token, Expression> Binary =
    Parse.Chain(Operator, Literal, MakeBinary);

public static readonly TokenListParser<Token, Expression> Operand =
    Unary.Try().Or(Binary);

public static readonly TokenListParser<Token, Expression> Conditional =
    Parse.Chain(Boolean, Operand, MakeBinary);
```

And/Or/Not/Exists/etc. are all simple token matches defined similarly to this:

```C#
public static readonly TokenListParser<Token, Operators.Operator> And =
            Token.EqualTo(Token.And).Value(Operators.Operators.And);
```

and `Literal` is a bunch of literal values that store values in string form:

```C#
public static readonly TokenListParser<Token, Expression> Text =
            Token.EqualTo(Token.Text)
                .Select(t => (Expression)new ConstantExpression(t.ToStringValue().Trim('"')));

...

public static readonly TokenListParser<Token, Expression> Literal =
            Number.Or(Text)
                 .Or(HexNumber)
                 .Or(Reference)
                 .Or(BinaryState)
                 .Named("literal");
```

The issue right now is that a conditional that is just a lone Literal, without any operators, is allowed, when I need it to only allow combinations of a literal and an operator.

Illegal: `foo`
Legal: `foo is 1` or `bar exists`

I assume that since `.Chain` handles left-recursive chains it notices there is nothing to chain and just returns the first item, but is it possible to force there to be an operator when using `.Chain`?

**Comment by nblumhardt** [comment]
Hi! I think there are two possible approaches. I would tend towards enforcing this by post-processing the resulting AST, but it also should be possible to use something like:

```csharp
public static readonly TokenListParser<Token, Expression> Conditional =
    Parse.Chain(Boolean, Operand, MakeBinary)
        .Where(e => e is BinaryExpression);
```

Alternatively, you could modify `Chain()` to create your own combinator `ChainAtLeastOnce()`.

Do any of the above help? Cheers!

**Comment by RPiAwesomeness** [comment]
@nblumhardt Sorry about the delay in getting back to you, I did try to do something similar to both of those, but I was hoping there would be a way that in either of those methods I would be able to have access to the character/line number for the error message. The latter method does throw an ParseException automatically, but the message isn't helpful, and I haven't figured out how to get access to the positions within the different parts during post-processing.

Is it possible to do either of those? Preferably I would have it generate the error message, so it can happen earlier on during the parsing, but it would also be useful to know how to access the line/char/abs position after the parser runs.

If I were to modify `Chain()`, how would you suggest I go about that? I'm still fairly new to working with C# and libraries.

**Comment by nblumhardt** [comment]
Hi @RPiAwesomeness - some experimentation might be needed, but I think it should be enough to add a line at: https://github.com/datalust/superpower/blob/dev/src/Superpower/Parse.cs#L135

```csharp
if (!operatorResult.HasValue) return operatorResult;
```

This would be before the `while` loop begins, and would have the effect of failing the parse if the first attempt to parse an operator fails.

HTH!

**Comment by RPiAwesomeness** [comment]
So I could just edit that file in my local copy of Superpower? How would that work with future releases?

If I were to add a combinator like you mentioned (ex. `ChainAtLeastOnce`) how best should I go about submitting the pull request/handling testing/and all that?

**Comment by nblumhardt** [comment]
Hi! You'd just add `ChainAtLeastOnce()` to a new static class in your own project. As long as future Superpower versions don't break the signatures of underlying parser/result types, this would just keep working.

I don't think we'd accept this via a PR currently, as although it's the right thing to do in your scenario, it's probably not general enough to warrant adding to the core library right now (there's a huge space of possible parsing tactics, so it'd be easy to bloat Superpower out unintentionally).

HTH, and let me know if you need a hand getting `ChainAtLeastOnce()` up and running! 👍

**Comment by RPiAwesomeness** [comment]
I finally have had time to get back around to working on this again and in trying what you suggested I ran into two issues when I attempted to build it:

```
1>Parser\Mixins.cs(60,54,60,68): error CS0029: Cannot implicitly convert type 'Superpower.Model.TokenListParserResult<TKind, TOperator>' to 'Superpower.Model.TokenListParserResult<TKind, T>'
1>Parser\Mixins.cs(60,54,60,68): error CS1662: Cannot convert lambda expression to intended delegate type because some of the return types in the block are not implicitly convertible to the delegate return type
1>Parser\Mixins.cs(62,66,62,75): error CS1061: 'TokenListParserResult<TKind, TOperator>' does not contain a definition for 'IsPartial' and no accessible extension method 'IsPartial' accepting a first argument of type 'TokenListParserResult<TKind, TOperator>' could be found (are you missing a using directive or an assembly reference?)
``

I wasn't sure exactly what you meant, so I tried copying the `Chain()` function code directly and adding the line as you suggested. I assume there is a better way to approach this, but that made the most sense to me as the first thing to try.

The first error makes sense to me, I just need to be able to return the correct type when I return early and the result from `@operator()` doesn't match the second type.

As for the second error, is this something that I can resolve by adding a reference to a certain part of Superpower? According to Visual Studio it's an internal method that I don't have access to in my code.

**Comment by nblumhardt** [comment]
Hope you found a solution to this; closing as the thread's now a bit stale 👋
