### ISSUE TITLE
Many with partial match consumes to much of the input

### ISSUE THREAD

**Issue by SeeDee82** [datalust/superpower#76]
I'm trying build a parser to match text that would be recognized by the regular expression "(ab)*ac"

`var ab = Character.EqualTo('a').Then(_ => Character.EqualTo('b'));`
`var ac = Character.EqualTo('a').Then(_ => Character.EqualTo('c'));`
`var list = ab.Try().Many().Then(ac);`

This should match the input "ababac". However `Many(...)` will consume the "a" in "ac" and thus the ac parser will fail. If I leave out the `Try()` then `Many(...)` will fail and the ac parser isn't even executed.

Am I missing something here? This seems like a bug to me, but I can't imagine that I'm the first to try this. Is there some other way to combine such parsers with partial matches? (I was originally trying to build an XML parser for educational purposes, where I had this issue with the '<' char)

Looking at the history it seems that this might have worked before the rewrite of backtracking. 

I know how I can change `Many()` so this is working, but I'm not sure if that would be the right place.

**Comment by nblumhardt** [comment]
Thanks for the report, @SeeDee82 - this is indeed a bug. I've created #78 to fix, including your test case.

I'll merge it through to `dev` so that a pre-release package is published; it would be fantastic if you can check that the new package behaves as you expect.

Thanks again!

**Comment by SeeDee82** [comment]
Thank you for the fast fix, this looks good.

On the subject of backtracking, can you explain why you decided to have backtracking only as opt-in. It seems to me that you would always want to have backtracking on by default. 
The only two places I could find where backtracking is used at all are the `Many` and `Or` combinators, and in both cases I think you would expect partial failure and need the ability to try the next parser regardless of the reason for or the internal state after the failure.
