### ISSUE TITLE
Chain combinator question

### ISSUE THREAD

**Issue by xtofs** [datalust/superpower#81]
Hi, 

I am trying to find a more idiomatic way to write a token list parser for something like  `variable.propertyA.propertyB` ". 
I believe this can be written recursively as something like `Reference = Variable | Reference '.' Identifier ` (with careful use of `Try`) where the '.'-token plays a role similar to an operator combined Reference and Identifier.

The chain operator can't be used since it expects a Func<TOperator, T, T, T> which means it combines two T's into a single T'.  (this somehow sounds analogous to fold and foldLeft).

I was hoping to find a built in combinator like Chain. Any suggestions?

**Comment by nblumhardt** [comment]
Hi Christof, thanks for the note. `Chain()` seems like the right overall approach - I wonder whether we could make the signature a bit more flexible? Are you able to experiment by creating a modified "chain" in your own solution that accepts `Func<TOperator, T, U, T>` or similar? Cheers!

**Comment by xtofs** [comment]
I solved it now through a combination of combinators and the .NET aggregate.

```
           from v in Variable
           from props in (
               from _ in Token.EqualTo(FilterExpressionToken.Dot)
               from p in Token.EqualTo(FilterExpressionToken.Identifier)
               select p
            ).Many()
           select 
                props.Aggregate(v, (e, p) => FilterExpression.Property(e, p.Span.ToStringValue()));
```

I will try to send a pull request when/if I succeed with an overloaded Chain that takes Func<TOperator, T, U, T>.
