### ISSUE TITLE
[QUESTION] Using SuperPower for creating a parser for a text adventure game

### ISSUE THREAD

**Issue by xDGameStudios** [datalust/superpower#95]
This is more a question than it is an issue... I wanted to know what would be the viability of creating a parser for a Text Adventure Game using SuperPower... for example to parse commands like:

`"TAKE SWORD OF LIGHT FROM THE STONE"`
`"EXIT TO THE KITCHEN"`

**Comment by nblumhardt** [comment]
Hi! Unfortunately I don't have the experience to offer any useful suggestions, here, but I suspect starting with something aimed at natural language processing would be a better bet. Keen to see if anyone else out there has ideas to add :-)

**Comment by xDGameStudios** [comment]
I was leaned to use something like SuperPower or a custom one based on superpower because I want developers using my framework to be able to add custom commands with ease... so I was thinking something like:

```csharp
CommandParser.addCommand(
     parser =>
          from verb in Word("TAKE").Or(Word("GRAB"))
          from @object in Object(ObjectOptions.InScope, ObjectOptions.NotHeld)
          select new Dictionary<string, string>() { {"verb", verb}, {"object": @object} }
)
```

Then the command parser would go though all the entries in it till it matches one!
I was convinced that Natural Language Processing would be too overwhelming.

**Comment by xDGameStudios** [comment]
@nblumhardt by the way and regarding my last post, how could I make a `In("word1", "word2")` method for Span for matching one of the words?
